<?php

namespace App;

use App\Product;
use App\Scopes\SellerScope;
use App\Transformers\SellerTransformer;

class Seller extends User
{
    public $transformer= SellerTransformer::class;

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new SellerScope());
    }

    /**
     * TODO un vendedor tiene muchos productos
     * https://styde.net/laravel-6-doc-eloquent-relaciones/#one-to-many
     */
    public function products()
    {
        return $this->hasMany(Product::class);
    }
}
